-- Migration: Fix public_system_settings view to restore missing columns
-- Description: Recreates the public_system_settings view to include missing columns like notification_tone, vibration patterns, mashup settings, withdrawal parameters, and recommender toggles that were omitted in a previous migration.

DROP VIEW IF EXISTS public.public_system_settings CASCADE;

CREATE OR REPLACE VIEW public.public_system_settings WITH (security_invoker = true) AS
SELECT 
  id,
  auto_api_switch,
  holiday_mode_enabled,
  holiday_message,
  disable_ordering,
  dark_mode_enabled,
  store_visitor_popup_enabled,
  customer_service_number,
  support_channel_link,
  mtn_markup_percentage,
  telecel_markup_percentage,
  at_markup_percentage,
  free_data_enabled,
  free_data_network,
  free_data_package_size,
  free_data_max_claims,
  free_data_claims_count,
  auto_pending_sms_enabled,
  show_announcement,
  announcement_title,
  announcement_message,
  maintenance_mode,
  registration_enabled,
  whatsapp_bot_prompt,
  home_page_video_url,
  home_page_video_muted,
  agent_activation_fee,
  sub_agent_base_fee,
  show_scrolling_ad,
  scrolling_ad_text,
  scrolling_ad_image_url,
  traditional_background_enabled,
  background_custom_image_url,
  wassce_price,
  bece_price,
  enable_privacy_shield,
  maintenance_message,
  maintenance_started_at,
  maintenance_eta,
  withdrawal_auto_approve_enabled,
  withdrawal_auto_approve_max_amount,
  withdrawal_auto_approve_min_age_days,
  withdrawal_auto_approve_require_no_chargebacks,
  free_agent_promo_enabled,
  free_agent_promo_limit,
  free_agent_promo_claimed,
  tutorial_buy_video_url,
  tutorial_agent_video_url,
  tutorial_subagent_video_url,
  min_withdrawal_amount,
  withdrawal_system_enabled,
  max_withdrawal_amount,
  paystack_deposit_fee_percent,
  withdrawal_fee_flat,
  withdrawal_fee_percent,
  welcome_promo_enabled,
  notification_tone,
  notification_vibration_enabled,
  notification_vibration_pattern,
  vendor_min_transaction,
  ai_recommender_enabled,
  world_cup_predictor_enabled,
  background_brightness,
  background_contrast,
  background_blueness,
  mashup_automation_enabled,
  mashup_export_threshold,
  mashup_whatsapp_number,
  mashup_delivery_delay_mins,
  active_payment_gateway,
  auto_refund_enabled,
  auto_gateway_switch_by_package,
  beneficiary_verification_enabled,
  manual_fulfillment_mode,
  allow_non_beneficiary_continue,
  updated_at
FROM public.system_settings;

GRANT SELECT ON public.public_system_settings TO anon, authenticated, service_role;
COMMENT ON VIEW public.public_system_settings IS 'Unified secured subset of system settings visible to frontend users and dynamic layout hooks.';
