-- Add auto_gateway_switch_by_package to system_settings
ALTER TABLE public.system_settings ADD COLUMN IF NOT EXISTS auto_gateway_switch_by_package BOOLEAN DEFAULT FALSE;

-- Recreate public_system_settings view to expose it safely to authenticated/anonymous users
DROP VIEW IF EXISTS public.public_system_settings CASCADE;
CREATE VIEW public.public_system_settings WITH (security_invoker = true) AS
 SELECT system_settings.id,
    system_settings.disable_ordering,
    system_settings.dark_mode_enabled,
    system_settings.store_visitor_popup_enabled,
    system_settings.customer_service_number,
    system_settings.support_channel_link,
    system_settings.holiday_mode_enabled, 
    system_settings.holiday_message,
    system_settings.mtn_markup_percentage, 
    system_settings.telecel_markup_percentage, 
    system_settings.at_markup_percentage,
    system_settings.auto_pending_sms_enabled, 
    system_settings.show_announcement, 
    system_settings.announcement_title, 
    system_settings.announcement_message,
    system_settings.free_data_enabled, 
    system_settings.free_data_network, 
    system_settings.free_data_package_size,
    system_settings.free_data_max_claims, 
    system_settings.free_data_claims_count,
    system_settings.home_page_video_url, 
    system_settings.home_page_video_muted,
    system_settings.withdrawal_auto_approve_enabled, 
    system_settings.withdrawal_auto_approve_max_amount,
    system_settings.withdrawal_auto_approve_min_age_days, 
    system_settings.withdrawal_auto_approve_require_no_chargebacks,
    system_settings.min_withdrawal_amount, 
    system_settings.max_withdrawal_amount, 
    system_settings.withdrawal_system_enabled,
    system_settings.paystack_deposit_fee_percent, 
    system_settings.withdrawal_fee_flat, 
    system_settings.withdrawal_fee_percent,
    system_settings.traditional_background_enabled, 
    system_settings.background_custom_image_url, 
    system_settings.enable_privacy_shield,
    system_settings.show_scrolling_ad, 
    system_settings.scrolling_ad_text, 
    system_settings.scrolling_ad_image_url,
    system_settings.agent_activation_fee, 
    system_settings.sub_agent_base_fee, 
    system_settings.wassce_price, 
    system_settings.bece_price,
    system_settings.maintenance_mode, 
    system_settings.maintenance_message, 
    system_settings.whatsapp_bot_prompt,
    system_settings.auto_api_switch,
    system_settings.tutorial_buy_video_url, 
    system_settings.tutorial_agent_video_url, 
    system_settings.tutorial_subagent_video_url,
    system_settings.free_agent_promo_enabled,
    system_settings.free_agent_promo_limit,
    system_settings.free_agent_promo_claimed,
    system_settings.notification_tone,
    system_settings.notification_vibration_enabled,
    system_settings.notification_vibration_pattern,
    system_settings.ai_recommender_enabled,
    system_settings.world_cup_predictor_enabled,
    system_settings.mashup_automation_enabled,
    system_settings.mashup_export_threshold,
    system_settings.mashup_whatsapp_number,
    system_settings.mashup_delivery_delay_mins,
    system_settings.auto_gateway_switch_by_package,
    system_settings.welcome_promo_enabled,
    system_settings.active_payment_gateway,
    system_settings.auto_refund_enabled,
    system_settings.vendor_min_transaction,
    system_settings.updated_at
   FROM public.system_settings;

GRANT SELECT ON public.public_system_settings TO anon, authenticated, service_role;
COMMENT ON VIEW public.public_system_settings IS 'Secured subset of system configurations visible to end users and dynamic layout hooks.';
